### ISSUE TITLE
Videos not loading in Ayamel player

### ISSUE THREAD

**Issue by dro248** [BYU-ARCLITE/Ayamel.js#15]
![youtube_mini](https://cloud.githubusercontent.com/assets/11342204/8224487/017b7b26-1545-11e5-9ce8-8ecded379e6a.png)

Youtube videos no longer load in the Ayamel player, meaning that they now show up as small, embedded Youtube videos.

**Comment by gliese1337** [comment]
Something similar has happened once before- issue #7 
Unfortunately, Dallas didn't specify exactly what the fix was when he closed the issue, but you can probably figure it out by examining the commit history around that time. With any luck, it'll turn out to be a similar issue, and that earlier fix will be helpful.

**Comment by johnlarson** [comment]
I think that actually came from me mistakenly pushing my work on Ayamel.js
to the origin develop branch. I've made a quick fix, but the sidebar
content doesn't show. Is there a way I can remove those changes from the
develop branch?
